-- 建立資料庫（如果不存在）
CREATE DATABASE IF NOT EXISTS sms_system;

-- 使用資料庫
\c sms_system;

-- 建立客戶基本資料表
CREATE TABLE IF NOT EXISTS public."custInfo"
(
    "CustId" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "CustName" character varying(20) COLLATE pg_catalog."default",
    "Gender" character varying(4) COLLATE pg_catalog."default",
    "MobileNumber" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "HomeNumber" character varying(15) COLLATE pg_catalog."default",
    "Address" character varying(200) COLLATE pg_catalog."default",
    "Age" integer,
    "Birthday" date,
    "Refuse" boolean,
    "CreateDate" timestamp without time zone,
    CONSTRAINT "custInfo_pkey" PRIMARY KEY ("CustId")
);

-- 建立訂單主資料表
CREATE TABLE IF NOT EXISTS public."orderMaster"
(
    "OrderNo" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "OrderDate" timestamp without time zone,
    "CustId" character varying(20) COLLATE pg_catalog."default",
    "Amount" real,
    "PayMethod" smallint,
    "DeliveryAddress" character varying(200) COLLATE pg_catalog."default",
    "Receiver" character varying(20) COLLATE pg_catalog."default",
    "ReceiverPhone" character varying(20) COLLATE pg_catalog."default",
    "OrderType" smallint,
    "TakerId" character varying(10) COLLATE pg_catalog."default",
    "CreateDate" timestamp without time zone,
    CONSTRAINT "orderMaster_pkey" PRIMARY KEY ("OrderNo"),
    CONSTRAINT ordermaster_fkey_custid FOREIGN KEY ("CustId")
        REFERENCES public."custInfo" ("CustId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

-- 建立訂單明細資料表
CREATE TABLE IF NOT EXISTS public."orderDetail"
(
    rowkey integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OrderNo" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "ProductId" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "ProductTitle" character varying(20) COLLATE pg_catalog."default",
    "UnitPrice" real NOT NULL,
    "Qty" smallint NOT NULL,
    "BatchNo" character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT "orderDetail_pkey" PRIMARY KEY (rowkey),
    CONSTRAINT "orderDetail_fkey_OrderNo" FOREIGN KEY ("OrderNo")
        REFERENCES public."orderMaster" ("OrderNo") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 建立簡訊發送清單資料表
CREATE TABLE IF NOT EXISTS public."smsMessage"
(
    smskey integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CreateDate" timestamp without time zone NOT NULL,
    "MessageClass" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "MessageBody" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "RecipientNo" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "ScheduleDate" timestamp without time zone,
    "SendDate" timestamp without time zone,
    "ReturnCode" character varying(10) COLLATE pg_catalog."default",
    "ReturnMessage" character varying(500) COLLATE pg_catalog."default",
    "MessageId" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "smsMessage_pkey" PRIMARY KEY (smskey)
);

-- 建立索引
CREATE INDEX IF NOT EXISTS "custInfo_index_CustId"
    ON public."custInfo" USING btree
    ("CustId" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (deduplicate_items=True);

CREATE INDEX IF NOT EXISTS fki_ordermaster_fkey_custid
    ON public."orderMaster" USING btree
    ("CustId" COLLATE pg_catalog."default" ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS "fki_orderDetail_fkey_OrderNo"
    ON public."orderDetail" USING btree
    ("OrderNo" COLLATE pg_catalog."default" ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS "smsMessage_index_RecipientNo"
    ON public."smsMessage" USING btree
    ("RecipientNo" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (deduplicate_items=True);

-- 加入註解
COMMENT ON TABLE public."custInfo" IS '客戶基本資料表';
COMMENT ON COLUMN public."custInfo"."CustId" IS '客戶編號';
COMMENT ON COLUMN public."custInfo"."CustName" IS '客戶姓名';
COMMENT ON COLUMN public."custInfo"."Gender" IS '客戶性別';
COMMENT ON COLUMN public."custInfo"."MobileNumber" IS '行動電話號碼';
COMMENT ON COLUMN public."custInfo"."HomeNumber" IS '住家電話號碼';
COMMENT ON COLUMN public."custInfo"."Address" IS '通訊地址';
COMMENT ON COLUMN public."custInfo"."Age" IS '年齡';
COMMENT ON COLUMN public."custInfo"."Birthday" IS '生日';
COMMENT ON COLUMN public."custInfo"."Refuse" IS '拒絕電話聯絡';
COMMENT ON COLUMN public."custInfo"."CreateDate" IS '資料建立日期';

COMMENT ON TABLE public."orderMaster" IS '訂單主資料表';
COMMENT ON COLUMN public."orderMaster"."OrderNo" IS '訂單編號';
COMMENT ON COLUMN public."orderMaster"."OrderDate" IS '訂購日期';
COMMENT ON COLUMN public."orderMaster"."CustId" IS '客戶編號';
COMMENT ON COLUMN public."orderMaster"."Amount" IS '訂單金額';
COMMENT ON COLUMN public."orderMaster"."PayMethod" IS '付款方式';
COMMENT ON COLUMN public."orderMaster"."DeliveryAddress" IS '送貨地址';
COMMENT ON COLUMN public."orderMaster"."Receiver" IS '收貨人';
COMMENT ON COLUMN public."orderMaster"."ReceiverPhone" IS '收貨人電話';
COMMENT ON COLUMN public."orderMaster"."OrderType" IS '訂單類別';
COMMENT ON COLUMN public."orderMaster"."TakerId" IS '接單人員編號';
COMMENT ON COLUMN public."orderMaster"."CreateDate" IS '資料建立日期';

COMMENT ON TABLE public."orderDetail" IS '訂單明細資料表';
COMMENT ON COLUMN public."orderDetail"."OrderNo" IS '訂單編號';
COMMENT ON COLUMN public."orderDetail"."ProductId" IS '產品編號';
COMMENT ON COLUMN public."orderDetail"."ProductTitle" IS '產品名稱';
COMMENT ON COLUMN public."orderDetail"."UnitPrice" IS '單價';
COMMENT ON COLUMN public."orderDetail"."Qty" IS '數量';
COMMENT ON COLUMN public."orderDetail"."BatchNo" IS '產品批號';

COMMENT ON TABLE public."smsMessage" IS '簡訊發送清單資料表';
COMMENT ON COLUMN public."smsMessage"."CreateDate" IS '資料建立日期';
COMMENT ON COLUMN public."smsMessage"."MessageClass" IS '簡訊類別';
COMMENT ON COLUMN public."smsMessage"."MessageBody" IS '簡訊內文';
COMMENT ON COLUMN public."smsMessage"."RecipientNo" IS '收訊者電話, 可多筆，以,區隔';
COMMENT ON COLUMN public."smsMessage"."ScheduleDate" IS '預約發送日期時間';
COMMENT ON COLUMN public."smsMessage"."SendDate" IS '簡訊發送日期';
COMMENT ON COLUMN public."smsMessage"."ReturnCode" IS '回覆代碼';
COMMENT ON COLUMN public."smsMessage"."ReturnMessage" IS '回覆訊息';
COMMENT ON COLUMN public."smsMessage"."MessageId" IS '回覆訊息編號';