-- 建立資料庫（如果不存在）
CREATE DATABASE IF NOT EXISTS sms_system;

-- 使用資料庫
\c sms_system;

-- 建立客戶基本資料表
CREATE TABLE IF NOT EXISTS public.cust_info
(
    cust_id character varying(20) COLLATE pg_catalog.default NOT NULL,
    cust_name character varying(20) COLLATE pg_catalog.default,
    gender character varying(4) COLLATE pg_catalog.default,
    mobile_number character varying(15) COLLATE pg_catalog.default NOT NULL,
    home_number character varying(15) COLLATE pg_catalog.default,
    address character varying(200) COLLATE pg_catalog.default,
    age integer,
    birthday date,
    refuse boolean,
    create_date timestamp without time zone,
    CONSTRAINT cust_info_pkey PRIMARY KEY (cust_id)
);

-- 建立訂單主資料表
CREATE TABLE IF NOT EXISTS public.order_master
(
    order_no character varying(20) COLLATE pg_catalog.default NOT NULL,
    order_date timestamp without time zone,
    cust_id character varying(20) COLLATE pg_catalog.default,
    amount real,
    pay_method smallint,
    delivery_address character varying(200) COLLATE pg_catalog.default,
    receiver character varying(20) COLLATE pg_catalog.default,
    receiver_phone character varying(20) COLLATE pg_catalog.default,
    order_type smallint,
    taker_id character varying(10) COLLATE pg_catalog.default,
    create_date timestamp without time zone,
    CONSTRAINT order_master_pkey PRIMARY KEY (order_no),
    CONSTRAINT order_master_fkey_cust_id FOREIGN KEY (cust_id)
        REFERENCES public.cust_info (cust_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

-- 建立訂單明細資料表
CREATE TABLE IF NOT EXISTS public.order_detail
(
    rowkey integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    order_no character varying(20) COLLATE pg_catalog.default NOT NULL,
    product_id character varying(20) COLLATE pg_catalog.default NOT NULL,
    product_title character varying(20) COLLATE pg_catalog.default,
    unit_price real NOT NULL,
    qty smallint NOT NULL,
    batch_no character varying(10) COLLATE pg_catalog.default,
    CONSTRAINT order_detail_pkey PRIMARY KEY (rowkey),
    CONSTRAINT order_detail_fkey_order_no FOREIGN KEY (order_no)
        REFERENCES public.order_master (order_no) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 建立簡訊發送清單資料表
CREATE TABLE IF NOT EXISTS public.sms_message
(
    smskey integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    create_date timestamp without time zone NOT NULL,
    message_class character varying(10) COLLATE pg_catalog.default NOT NULL,
    message_body character varying(200) COLLATE pg_catalog.default NOT NULL,
    recipient_no character varying(1000) COLLATE pg_catalog.default NOT NULL,
    schedule_date timestamp without time zone,
    send_date timestamp without time zone,
    return_code character varying(10) COLLATE pg_catalog.default,
    return_message character varying(500) COLLATE pg_catalog.default,
    message_id character varying(50) COLLATE pg_catalog.default,
    CONSTRAINT sms_message_pkey PRIMARY KEY (smskey)
);

-- 建立索引
CREATE INDEX IF NOT EXISTS cust_info_index_cust_id
    ON public.cust_info USING btree
    (cust_id COLLATE pg_catalog.default ASC NULLS LAST)
    WITH (deduplicate_items=True);

CREATE INDEX IF NOT EXISTS fki_order_master_fkey_cust_id
    ON public.order_master USING btree
    (cust_id COLLATE pg_catalog.default ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS fki_order_detail_fkey_order_no
    ON public.order_detail USING btree
    (order_no COLLATE pg_catalog.default ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS sms_message_index_recipient_no
    ON public.sms_message USING btree
    (recipient_no COLLATE pg_catalog.default ASC NULLS LAST)
    WITH (deduplicate_items=True);

-- 加入註解
COMMENT ON TABLE public.cust_info IS '客戶基本資料表';
COMMENT ON COLUMN public.cust_info.cust_id IS '客戶編號';
COMMENT ON COLUMN public.cust_info.cust_name IS '客戶姓名';
COMMENT ON COLUMN public.cust_info.gender IS '客戶性別';
COMMENT ON COLUMN public.cust_info.mobile_number IS '行動電話號碼';
COMMENT ON COLUMN public.cust_info.home_number IS '住家電話號碼';
COMMENT ON COLUMN public.cust_info.address IS '通訊地址';
COMMENT ON COLUMN public.cust_info.age IS '年齡';
COMMENT ON COLUMN public.cust_info.birthday IS '生日';
COMMENT ON COLUMN public.cust_info.refuse IS '拒絕電話聯絡';
COMMENT ON COLUMN public.cust_info.create_date IS '資料建立日期';

COMMENT ON TABLE public.order_master IS '訂單主資料表';
COMMENT ON COLUMN public.order_master.order_no IS '訂單編號';
COMMENT ON COLUMN public.order_master.order_date IS '訂購日期';
COMMENT ON COLUMN public.order_master.cust_id IS '客戶編號';
COMMENT ON COLUMN public.order_master.amount IS '訂單金額';
COMMENT ON COLUMN public.order_master.pay_method IS '付款方式';
COMMENT ON COLUMN public.order_master.delivery_address IS '送貨地址';
COMMENT ON COLUMN public.order_master.receiver IS '收貨人';
COMMENT ON COLUMN public.order_master.receiver_phone IS '收貨人電話';
COMMENT ON COLUMN public.order_master.order_type IS '訂單類別';
COMMENT ON COLUMN public.order_master.taker_id IS '接單人員編號';
COMMENT ON COLUMN public.order_master.create_date IS '資料建立日期';

COMMENT ON TABLE public.order_detail IS '訂單明細資料表';
COMMENT ON COLUMN public.order_detail.order_no IS '訂單編號';
COMMENT ON COLUMN public.order_detail.product_id IS '產品編號';
COMMENT ON COLUMN public.order_detail.product_title IS '產品名稱';
COMMENT ON COLUMN public.order_detail.unit_price IS '單價';
COMMENT ON COLUMN public.order_detail.qty IS '數量';
COMMENT ON COLUMN public.order_detail.batch_no IS '產品批號';

COMMENT ON TABLE public.sms_message IS '簡訊發送清單資料表';
COMMENT ON COLUMN public.sms_message.create_date IS '資料建立日期';
COMMENT ON COLUMN public.sms_message.message_class IS '簡訊類別';
COMMENT ON COLUMN public.sms_message.message_body IS '簡訊內文';
COMMENT ON COLUMN public.sms_message.recipient_no IS '收訊者電話, 可多筆，以,區隔';
COMMENT ON COLUMN public.sms_message.schedule_date IS '預約發送日期時間';
COMMENT ON COLUMN public.sms_message.send_date IS '簡訊發送日期';
COMMENT ON COLUMN public.sms_message.return_code IS '回覆代碼';
COMMENT ON COLUMN public.sms_message.return_message IS '回覆訊息';
COMMENT ON COLUMN public.sms_message.message_id IS '回覆訊息編號';
